services:
  php81-benchmark:
    image: php:8.1-cli
    volumes:
      - ./benchmarks:/usr/src/benchmark/benchmarks
      - ./benchmark.php:/usr/src/benchmark/benchmark.php
    working_dir: /usr/src/benchmark
    command: ["php", "./benchmark.php"]

  php82-benchmark:
    image: php:8.2-cli
    volumes:
      - ./benchmarks:/usr/src/benchmark/benchmarks
      - ./benchmark.php:/usr/src/benchmark/benchmark.php
    working_dir: /usr/src/benchmark
    command: ["php", "./benchmark.php"]

  php83-benchmark:
    image: php:8.3-cli
    volumes:
      - ./benchmarks:/usr/src/benchmark/benchmarks
      - ./benchmark.php:/usr/src/benchmark/benchmark.php
    working_dir: /usr/src/benchmark
    command: ["php", "./benchmark.php"]

  php84-benchmark:
    image: php:8.4.0alpha4-cli
    volumes:
      - ./benchmarks:/usr/src/benchmark/benchmarks
      - ./benchmark.php:/usr/src/benchmark/benchmark.php
    working_dir: /usr/src/benchmark
    command: ["php", "./benchmark.php"]
